# Generated by Django 3.1.6 on 2023-05-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_merge_20190815_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='idade',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cep',
            field=models.CharField(max_length=8, verbose_name='CEP (Somente números)'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF (Somente números)'),
        ),
    ]
