# Generated by Django 4.1.7 on 2023-03-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_auto_20190815_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variacao',
            name='nome',
        ),
        migrations.AddField(
            model_name='variacao',
            name='nome_v',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
