# Generated by Django 4.1.7 on 2023-03-29 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0010_remove_variacao_nome_variacao_nome_v'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variacao',
            old_name='nome_v',
            new_name='nome',
        ),
    ]
