# Generated by Django 4.1.7 on 2023-03-29 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0011_rename_nome_v_variacao_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variacao',
            name='nome',
        ),
    ]
