# Generated by Django 4.1.7 on 2023-03-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0012_remove_variacao_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacao',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
