# Generated by Django 4.1.7 on 2023-03-29 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0013_variacao_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacao',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.produto'),
        ),
    ]
