# Generated by Django 3.1 on 2023-04-19 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0015_alter_variacao_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto'),
        ),
    ]
