# Generated by Django 3.1.6 on 2023-05-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0017_auto_20230420_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('O', 'Outro'), ('M', 'Masculino'), ('F', 'Femenino'), ('I', 'Infantil'), ('A', 'Acessórios')], default='O', max_length=1),
        ),
    ]
