# Generated by Django 3.1.6 on 2023-06-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0019_auto_20230530_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacao',
            name='nome',
            field=models.CharField(blank=True, db_column='variacao_nome', max_length=50, null=True),
        ),
    ]
