# Generated by Django 3.1.6 on 2023-06-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0020_auto_20230618_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacao',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
