# Generated by Django 3.1.6 on 2023-06-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0021_auto_20230618_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacao',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='variacao',
            name='tipo',
            field=models.CharField(choices=[('O', 'Outro'), ('M', 'Masculino'), ('F', 'Feminino'), ('I', 'Infantil'), ('A', 'Acessórios')], default='O', max_length=1),
        ),
    ]
