# Generated by Django 3.1.6 on 2023-06-18 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0022_auto_20230618_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variacao',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='variacao',
            name='tipo',
        ),
    ]
