# Generated by Django 3.1.6 on 2023-06-19 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0023_auto_20230618_1943'),
        ('pedido', '0004_pedido_data_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='fk_produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.produto'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='fk_variacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.variacao'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='produto_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='variacao_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
